version: '3.1'

services:
  postgres:
    image: postgres:9.5-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/data/db
      - ./pg_bkup:/backup

  node:
    build: .
    image: devx/recruiting
    ports:
      - "8080:8080"
    links:
      - postgres
    restart: always
    env_file:
      - node.dev.env

volumes:
  postgres_data:
